[package]
name = "dex-client"
description = "IPC client for the DEX runtime. Protocol only, no presentation."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
dex-protocol = { workspace = true }

anyhow = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
